version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    user: '1000'
    environment:
      - "XDEBUG_CONFIG=remote_host=192.168.2.16"
      - "PHP_IDE_CONFIG=serverName=wolmanager.devel"
  web:
    image: nginx:alpine
    volumes:
      - ./:/app
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    environment:
      - "VIRTUAL_HOST=wolmanager.devel"

networks:
  default:
    external:
      name: webdev-net